tenants:
  - id: tenant1
    uid: 1000
    gid: 1000
    api_key: "test_key_1"
    max_overlays: 2
    max_buffers: 10
    max_memory_mb: 256
    allowed_bitstreams:
      - "conv2d.bit"
    allowed_address_ranges:
      - [0xA0000000, 0x10000]
      - [0xA0010000, 0x10000]  # axi_gpio_0
      - [0xA0020000, 0x10000]  # axi_gpio_0
