# config.yaml 
global:
  num_pr_zones: 4
  bitstream_dir: /home/xilinx/bitstreams
  socket_dir: /var/run/pynq
  static_bitstream: /home/xilinx/bitstreams/full.bit
  

  pr_zones:
    - zone_id: 0
      name: PR_0
      gpio_pin: 0
      address_ranges:
        - [0xB0000000, 0x10000]  

    
    - zone_id: 1
      name: PR_1
      gpio_pin: 1
      address_ranges:
        - [0xB0010000, 0x10000] 
    
    - zone_id: 2
      name: PR_2
      gpio_pin: 2
      address_ranges:
        - [0xB0020000, 0x10000] 

    
    - zone_id: 3
      name: PR_3
      gpio_pin: 3
      address_ranges:
        - [0xB0030000, 0x10000]        
  


tenants:
  - id: tenant1
    uid: 1001
    gid: 1001
    api_key: test_key_1
    max_overlays: 2
    max_buffers: 10
    max_memory_mb: 256
    allowed_bitstreams:
      - PR_0_bit_0.bit
      - PR_0_bit_1.bit
      - PR_1_bit_0.bit
      - PR_1_bit_1.bit
      - PR_2_bit_0.bit
      - PR_2_bit_1.bit
      - PR_3_bit_0.bit
      - PR_3_bit_1.bit
    allowed_pr_zones: [0, 1, 2, 3]

  - id: tenant2
    uid: 1002
    gid: 1002
    api_key: test_key_2
    max_overlays: 1
    max_buffers: 5
    max_memory_mb: 128
    allowed_bitstreams:
      - PR_0_bit_0.bit
      - PR_0_bit_1.bit
      - PR_1_bit_0.bit
      - PR_1_bit_1.bit
      - PR_2_bit_0.bit
      - PR_2_bit_1.bit
      - PR_3_bit_0.bit
      - PR_3_bit_1.bit
    allowed_pr_zones: [0, 1, 2, 3]


  - id: tenant3
    uid: 1003
    gid: 1003
    api_key: test_key_3
    max_overlays: 1
    max_buffers: 5
    max_memory_mb: 128
    allowed_bitstreams:
      - PR_0_bit_0.bit
      - PR_0_bit_1.bit
      - PR_1_bit_0.bit
      - PR_1_bit_1.bit
      - PR_2_bit_0.bit
      - PR_2_bit_1.bit
      - PR_3_bit_0.bit
      - PR_3_bit_1.bit
    allowed_pr_zones: [0, 1, 2, 3]


  - id: tenant4
    uid: 1004
    gid: 1004
    api_key: test_key_4
    max_overlays: 1
    max_buffers: 5
    max_memory_mb: 128
    allowed_bitstreams:
      - PR_0_bit_0.bit
      - PR_0_bit_1.bit
      - PR_1_bit_0.bit
      - PR_1_bit_1.bit
      - PR_2_bit_0.bit
      - PR_2_bit_1.bit
      - PR_3_bit_0.bit
      - PR_3_bit_1.bit
    allowed_pr_zones: [0, 1, 2, 3]